spring:
  profiles:
    active: dev   #配置文件版本
  security:
    basic:
      enable: true  #是否开启spring security基本的鉴权
  flyway:
    enabled: false   #是否启用flyway

##mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml
  typeEnumsPackage: org.honeybee.*.enums  # 配置扫描通用枚举， 支持统配符 * 或者 ; 分割
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

##jwt配置
auth:
  jwt:
    header: jwt-token
    secret: mySecret
    expiration: 3600 #token有效期一天(秒)
    # 不需要鉴权的路径
  ignores:
    - "/"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/**"
    - "/webjars/**"
    - "/doc.html"
    - "/api/**"

enums:
  param:
    suffix: Str   #实体类中的枚举字段返回的描述值后缀